### ISSUE TITLE
Server dont stop at all

### ISSUE THREAD

**Issue by Pela667** [Razzmatazzz/ValheimServerWarden#16]
when close serverwarden, dont kill valheim_server.exe

BTW: yo can add a FTP upload feature for backups?

Great work bud!

**Comment by Razzmatazzz** [comment]
Are you requesting that you should be able to close the app and leave the servers running? It's not possible to do that and still maintain the ability to monitor the output from the server processes. In other words, if you launch the app, start a server, close the app, and then reopen the app, you will no longer be able to see the status of the server you previously launched. That's why I made the app minimize to the system tray; it will stay out of your way while you leave it running. 

As for save backups, I recommend running Valheim Save Shield.

**Comment by Pela667** [comment]
I am also using your beautiful backup program.
both really look great to me.
so, it might be nice to add the option to upload to an ftp in the Valheim Save Shield, and an option in the Server Warden to enter seed when starting a new world.
It may be a lot, but they are only suggestions.
excellent work friend, thank you very much!

**Comment by Razzmatazzz** [comment]
For the option to upload to FTP in Valheim Save Shield, do you mean the option to restore a save to the FTP server that's configured for syncing world saves? That might be doable.

Unfortunately, there's currently no way to use a specific seed when creating a new world via the dedicated server, so I won't be able to add that option.

**Comment by Pela667** [comment]
_For the option to upload to FTP in Valheim Save Shield, do you mean the option to restore a save to the FTP server that's configured for syncing world saves?_ 

yeah!!!!
