### ISSUE TITLE
SteamCMD Update/check for update option

### ISSUE THREAD

**Issue by praramis** [Razzmatazzz/ValheimServerWarden#30]
when i right click on server go to details and then at the top left if i click check for steam cmd updates or update it is pointing to the wrong file location to look for appmanifest

**Comment by Razzmatazzz** [comment]
What makes it the wrong location? Where is the appmanifest stored for you?

**Comment by praramis** [comment]
sorry for late reply really quickly i just wanna say i really love both your apps and im a big fan of what youve done and i just want to say thank you for all your hard work and time you spent on these i greatly appreciate it

ok now to move on

i have all my folders selected correctly in the settings but every time it tries to auto update i can see its looking for it on this path

3/10/2021 2:41:59 AM: ARods Build Palace [NA East]: Could not find C:\Users\DeezNutz\Desktop\steamcmd\steamapps\common\Valheim dedicated server\steamapps\appmanifest_896660.acf for update check.

by default steamcmd has the appmanifest installed in 

C:\Users\DeezNutz\Desktop\steamcmd\steamapps\appmanifest_896660.acf

for some reason the update checks on your app is adding extra folders to look for it

**Comment by Razzmatazzz** [comment]
I gather that you installed the dedicated server via SteamCMD yourself (not using VSW) and didn't use the -force_install_dir parameter? The reason it's checking those "extra" folders is that when you use SteamCMD's -force_install_dir parameter to install a server to a specific location, it puts those additional folders in the server installation folder rather than in the SteamCMD folder. But it's easy enough to check for the server being installed in the "default" location, and I should have been checking for it anyway. Give the attached test build a try and see if it fixes the issue for you.
[vsw-steamcmd-fix-test.zip](https://github.com/Razzmatazzz/ValheimServerWarden/files/6116381/vsw-steamcmd-fix-test.zip)

**Comment by praramis** [comment]
will be trying this as soon as i get home will let you know

EDIT: So i installed and tested and it does not seem to work it did get rid of the error completely but the actual update check is not actually running nothing happens now same with the auto check almost as if it got turned off or something

**Comment by Razzmatazzz** [comment]
The update check actually doesn't display anything if it was successful and no update was available. I changed it to be that way because the "checking for update" messages started to overwhelm the server log (sort of like the "file not found" messages you were experiencing). But it should output something when the user manually checks for an update, so I'll change that. But if you're not seeing anything, that probably means it's working.

**Comment by Razzmatazzz** [comment]
The version I just released should tell you no update was available when you manually check. If that works for you, I think we're all set here.
