### ISSUE TITLE
Option to automatically stop servers and quit

### ISSUE THREAD

**Issue by jim-022** [Razzmatazzz/ValheimServerWarden#32]
Is it possible to add option in settings, something like Stop servers on Quit?
When you invoke quit the application goes and send stop action to all running servers and quits the Warden app.

**Comment by Razzmatazzz** [comment]
The app behaves the way it currently does to prevent people from exiting the app and either unintentionally killing their servers or leaving the server processes orphaned with no way to monitor them. I could probably add an option to shutdown all running servers on app close instead of requiring that servers be manually shutdown, but I'm still a bit wary of people unintentionally stopping their server(s). What's your use case that requires this feature?

**Comment by jim-022** [comment]
That's fine if it is your intend for the target audience, I can add it myself.

My use case is just for convinince, I am running single server for couple of friends and when managing the host it will be kind of quick but I love the idea of preventing shutdown by defualt.

**Comment by Razzmatazzz** [comment]
[vsw-test.zip](https://github.com/Razzmatazzz/ValheimServerWarden/files/6178375/vsw-test.zip)
This test version includes the setting to shutdown running servers when the app is closed. Note that this only works if you close the app "normally." If you end the process via task manager, there's no way to make sure the servers shut down gracefully along with the app.

**Comment by jim-022** [comment]
That was quick , thanks I will give it a try.

**Comment by Razzmatazzz** [comment]
Feature added in latest version.
