### ISSUE TITLE
Unicode support for Player Names

### ISSUE THREAD

**Issue by trashken** [Razzmatazzz/ValheimServerWarden#37]
Non-western names gets sent to Discord as gibberish.

```
VSW log:
8/4/2021 10:17:26 pm: Hellheim: Player åŠ‰å¾·è¯ (76561198025467399) died
8/4/2021 9:42:25 pm: Hellheim: Player åŠ‰å¾·è¯ (76561198025467399) connected
Discord:
åŠ‰å¾·è¯ has entered the fray!
åŠ‰å¾·è¯ met an untimely demise.
```

**Comment by Razzmatazzz** [comment]
Based on the log you provided here, it appears player names are also displayed incorrectly in the app log. Is that correct? Player names might be output as gibberish from the server console. If that's the case, I'm not sure whether it's possible to correct the encoding. But I'll look into it.

**Comment by trashken** [comment]
Friend used chinese characters in Valheim and it displays properly in the game but comes out gibberish in VSW and Discord.

**Comment by Razzmatazzz** [comment]
This issue stems from a bug in the server program itself. I created a character with the name "的是不我" (apologies if this means anything; I chose random Chinese characters), started a dedicated server without using VSW, connected to see what the console output was, and this is what was output when my character connected:
`04/10/2021 08:58:49: Got character ZDOID from τÜäµÿ»Σ╕ìµêæ : 1954407581:1`

VSW simply parses the output from the server console, so the gibberish named is displayed in VSW because the gibberish name is output by the server. 

It seems the native console outputs using the encoding for Code page 437, but at some point along the process of VSW receiving redirected console output from the server, the encoding is changed to windows-1252. I can take the player name as received, convert it to bytes using the windows-1252 encoding, and then convert those bytes to UTF-8. That results in displaying the correct player names for me. It's possible that other computers won't be using Code page 437 encoding for console output and won't be using windows-1252 encoding for receiving redirected console output as these are regional encodings that can vary from computer to computer.

Please try this test build to see if it fixes the issue for you.
[vsw.zip](https://github.com/Razzmatazzz/ValheimServerWarden/files/6290220/vsw.zip)

**Comment by trashken** [comment]
Yes this works! great stuff!

**Comment by Razzmatazzz** [comment]
Ok, thanks for verifying. Latest release includes this fix.
