### ISSUE TITLE
can not disable restart

### ISSUE THREAD

**Issue by tuvok81** [Razzmatazzz/ValheimServerWarden#9]
Hey Ho .. when i have enable the "restart box" i can not disable it.
![grafik](https://user-images.githubusercontent.com/30367063/108873644-9f9c6500-75fb-11eb-9db7-88a22056a506.png)

**Comment by Razzmatazzz** [comment]
So you can click the box and it does uncheck, but if you click save, close the window, and reopen the window, it's checked again? If that's the case, it will be fixed in the next version.

If you're unable to uncheck the box (which is what it sounds like you're saying), I'm not sure what would be causing that.

**Comment by tuvok81** [comment]
No its the same Problem .. :(

**Comment by Razzmatazzz** [comment]
Fixed in latest release. Thanks for reporting.
